name: CI

on:
  push:

jobs:
  macos:
    strategy:
      matrix:
        xcode:
          - '26.4'

    name: macOS (Xcode ${{ matrix.xcode }})
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v7
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run tests
        id: run-tests
        run: make test-macos
      - name: Zip XCResult
        id: zip-xcresult
        if: failure() && steps.run-tests.conclusion == 'failure'
        run: cd .xcresults; zip -r xcresult-macos.zip macos.xcresult
      - name: Upload XCResult
        if: failure() && steps.zip-xcresult.conclusion == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: xcresult-macos.zip
          path: .xcresults/xcresult-macos.zip

  ios:
    strategy:
      matrix:
        xcode:
          - '26.4'

    name: iOS (Xcode ${{ matrix.xcode }})
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v7
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run tests
        id: run-tests
        run: make test-ios
      - name: Zip XCResult
        id: zip-xcresult
        if: failure() && steps.run-tests.conclusion == 'failure'
        run: cd .xcresults; zip -r xcresult-ios.zip ios.xcresult
      - name: Upload XCResult
        if: failure() && steps.zip-xcresult.conclusion == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: xcresult-ios.zip
          path: .xcresults/xcresult-ios.zip

  documentation:
    strategy:
      matrix:
        xcode:
          - '26.4'

    name: DocC (Xcode ${{ matrix.xcode }})
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v7
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build documentation
        run: make docs

  linux:
    strategy:
      matrix:
        swift:
          - '6.3'

    container: swift:${{ matrix.swift }}
    name: Linux (Swift ${{ matrix.swift }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: swift test

