name: CI

on:
  push:

jobs:
  macos:
    strategy:
      matrix:
        xcode:
          - "14.3.1"

    name: macOS 13 (Xcode ${{ matrix.xcode }})
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run tests
        id: run-tests
        run: make test-macos
      - name: Zip XCResult
        id: zip-xcresult
        if: failure() && steps.run-tests.conclusion == 'failure'
        run: cd .xcresults; zip -r xcresult-macos.zip macos.xcresult
      - name: Upload XCResult
        if: failure() && steps.zip-xcresult.conclusion == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: xcresult-macos.zip
          path: .xcresults/xcresult-macos.zip

  ubuntu:
    strategy:
      matrix:
        swift:
          - "5.7"

    name: Ubuntu (Swift ${{ matrix.swift }})
    runs-on: ubuntu-20.04
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - run: swift test

  windows:
    strategy:
      matrix:
        swift:
          - "5.9.1"

    name: Windows (Swift ${{ matrix.swift }})
    runs-on: windows-latest

    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-${{ matrix.swift }}-release
          tag: ${{ matrix.swift }}-RELEASE

      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4
      - run: swift build
      - run: swift test
